compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@babel/helper-create-class-features-plugin@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/helper-create-regexp-features-plugin@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/helper-define-polyfill-provider@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-async-generator-functions@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-export-namespace-from@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-logical-assignment-operators@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-nullish-coalescing-operator@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-object-rest-spread@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-proposal-optional-chaining@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-async-to-generator@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-block-scoped-functions@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-block-scoping@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-classes@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-computed-properties@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-destructuring@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-duplicate-keys@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-exponentiation-operator@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-for-of@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-member-expression-literals@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-modules-amd@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-modules-commonjs@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-modules-systemjs@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-modules-umd@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-new-target@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-object-super@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-parameters@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-property-literals@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-reserved-words@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-shorthand-properties@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-spread@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-sticky-regex@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-template-literals@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-typeof-symbol@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@babel/plugin-transform-unicode-escapes@*":
    dependencies:
      "@babel/core": ^7.18.2
  "@bluframe/blublocks@*":
    peerDependencies:
      styled-components: ^5.3.5
  babel-loader@*:
    dependencies:
      "@babel/core": ^7.18.2
  babel-plugin-polyfill-corejs2@*:
    dependencies:
      "@babel/core": ^7.18.2
  babel-plugin-polyfill-corejs3@*:
    dependencies:
      "@babel/core": ^7.18.2
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/nextjs": "*"
      react: "^18.2.0"
  "@storybook/nextjs@*":
    dependencies:
      "next": "^12.2.6"
      "webpack": "*" 
  "@storybook/react-dom-shim@*":
    dependencies:
      "react-dom": "^18.2.0"


yarnPath: .yarn/releases/yarn-4.0.2.cjs
